### ISSUE TITLE
✨ Feat: Entity 작성

### ISSUE THREAD

**Issue by lsmin3388** [Vision-Challengethon-TEAM-1/BackEnd#23]
### ✨ 기능 설명

- 식단 Entity 작성
- 일간 분석 Entity 작성
- 그룹 Entity 작성
- Proxy Entity 작성
- Base Entity 작성

---

### 📌 To-Do

- [x] 식단 Entity 작성
- [x] 일간 분석 Entity 작성
- [x] 그룹 Entity 작성
- [x] Proxy Entity 작성
- [x] Base Entity 작성

---

### 🙌🏻 기타 참고 사항

- x

---
