### ISSUE TITLE
✨ Feat: 인증/인가 기능 구현

### ISSUE THREAD

**Issue by lsmin3388** [Vision-Challengethon-TEAM-1/BackEnd#9]
### ✨ 기능 설명

- client는 구글 로그인을 할 수 있다.
- client는 구글 로그인 후 추가 개인정보 입력 여부를 알 수 있다.
- client는 구글 로그인 후 추가 개인정보 입력을 할 수 있다.
- client는 로그인 완료 시 JWT 토큰을 발급받을 수 있다.
- client는 로그아웃을 할 수 있다.

---

### 📌 To-Do

- [ ] Spring Security, Oauth2, Jwt 의존성 추가
- [ ] Member Entity 작성
- [ ] 의존성에 대한 Config 작성
- [ ] Cors Config 작성
- [ ] 구글 클라우드에서 Oauth2 API키 추가
- [ ] JWT Provider 작성
- [ ] 인증 관련 코드 작성
- [ ] 인가 관련 코드 작성

---

### 🙌🏻 기타 참고 사항

- Access Token과 Refresh Token은 모두 Cookie에서 관리하되, Refresh Token은 http-only가 붙어있습니다.
- 로컬에서는 잘 작동하지만 Cookie 보안 정책으로 SSL 인증서 적용 및 도메인 적용이 필요할 수 있습니다.
- 인증 관련 코드는 비즈니스 로직과 철저히 분리하여 의존 관계를 최소화합니다.

---
